export const SORT_BY_TOTAL_EARNINGS = "SORT_BY_TOTAL_EARNINGS";
export const FILTER_HARD_SUPPORT = "FILTER_HARD_SUPPORT";
export const FILTER_SOFT_SUPPORT = "FILTER_SOFT_SUPPORT";
export const FILTER_OFFLANE = "FILTER_OFFLANE";
export const FILTER_MIDLANE = "FILTER_MIDLANE";
export const FILTER_CARRY = "FILTER_CARRY";
export const ALL_PLAYERS = "ALL_PLAYERS"